"""initial_schema

Revision ID: 93fe35470006
Revises: 
Create Date: 2026-01-15 15:24:14.050777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fe35470006'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment primary key'),
    sa.Column('level', sa.String(), nullable=False, comment='Log severity: info, warning, error'),
    sa.Column('event_type', sa.String(), nullable=False, comment='Event category: scan, entry, error, config'),
    sa.Column('message', sa.Text(), nullable=False, comment='Human-readable log message'),
    sa.Column('details', sa.Text(), nullable=True, comment='Additional JSON-formatted details'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='When log was created (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_logs_level'), ['level'], unique=False)

    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False, comment='Steam App ID'),
    sa.Column('name', sa.String(), nullable=False, comment='Game/DLC/bundle name'),
    sa.Column('type', sa.String(), nullable=False, comment='Content type: game, dlc, or bundle'),
    sa.Column('release_date', sa.String(), nullable=True, comment='Release date from Steam'),
    sa.Column('review_score', sa.Integer(), nullable=False, comment='Overall review score (0-10), 0 means no reviews or unknown'),
    sa.Column('total_positive', sa.Integer(), nullable=False, comment='Number of positive reviews'),
    sa.Column('total_negative', sa.Integer(), nullable=False, comment='Number of negative reviews'),
    sa.Column('total_reviews', sa.Integer(), nullable=False, comment='Total number of reviews'),
    sa.Column('is_bundle', sa.Boolean(), nullable=False, comment='Whether this is a bundle'),
    sa.Column('bundle_content', sa.JSON(), nullable=True, comment='List of Steam App IDs in bundle'),
    sa.Column('game_id', sa.Integer(), nullable=True, comment='Main game App ID (for DLC/bundles)'),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True, comment='Last Steam API fetch time'),
    sa.Column('header_image', sa.String(length=512), nullable=True, comment='Steam header image URL'),
    sa.Column('description', sa.Text(), nullable=True, comment='Game description'),
    sa.Column('price', sa.Integer(), nullable=True, comment='Current price in cents (USD)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduler_state',
    sa.Column('id', sa.Integer(), nullable=False, comment='Singleton ID (always 1)'),
    sa.Column('last_scan_at', sa.DateTime(), nullable=True, comment='When last scan completed (UTC)'),
    sa.Column('next_scan_at', sa.DateTime(), nullable=True, comment='When next scan is scheduled (UTC)'),
    sa.Column('total_scans', sa.Integer(), nullable=False, comment='Total scans completed'),
    sa.Column('total_entries', sa.Integer(), nullable=False, comment='Total giveaways entered'),
    sa.Column('total_errors', sa.Integer(), nullable=False, comment='Total errors encountered'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phpsessid', sa.String(), nullable=True, comment='SteamGifts session cookie for authentication'),
    sa.Column('user_agent', sa.String(), nullable=False, comment='Browser user agent for HTTP requests'),
    sa.Column('xsrf_token', sa.String(), nullable=True, comment='Anti-CSRF token from SteamGifts'),
    sa.Column('dlc_enabled', sa.Boolean(), nullable=False, comment='Whether to enter DLC giveaways'),
    sa.Column('safety_check_enabled', sa.Boolean(), nullable=False, comment='Check giveaways for traps before auto-entering'),
    sa.Column('auto_hide_unsafe', sa.Boolean(), nullable=False, comment='Automatically hide unsafe giveaways on SteamGifts'),
    sa.Column('autojoin_enabled', sa.Boolean(), nullable=False, comment='Enable automatic giveaway entry'),
    sa.Column('autojoin_start_at', sa.Integer(), nullable=False, comment='Start entering when points >= this value'),
    sa.Column('autojoin_stop_at', sa.Integer(), nullable=False, comment='Stop entering when points <= this value'),
    sa.Column('autojoin_min_price', sa.Integer(), nullable=False, comment='Minimum giveaway price in points'),
    sa.Column('autojoin_min_score', sa.Integer(), nullable=False, comment='Minimum Steam review score (0-10)'),
    sa.Column('autojoin_min_reviews', sa.Integer(), nullable=False, comment='Minimum number of reviews required'),
    sa.Column('autojoin_max_game_age', sa.Integer(), nullable=True, comment='Maximum game age in years (None = no limit)'),
    sa.Column('scan_interval_minutes', sa.Integer(), nullable=False, comment='Scan interval in minutes'),
    sa.Column('max_entries_per_cycle', sa.Integer(), nullable=True, comment='Maximum entries per cycle (None = unlimited)'),
    sa.Column('automation_enabled', sa.Boolean(), nullable=False, comment='Master switch for automation'),
    sa.Column('max_scan_pages', sa.Integer(), nullable=False, comment='Maximum SteamGifts pages to scan'),
    sa.Column('entry_delay_min', sa.Integer(), nullable=False, comment='Minimum delay between entries (seconds)'),
    sa.Column('entry_delay_max', sa.Integer(), nullable=False, comment='Maximum delay between entries (seconds)'),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True, comment='Last sync with SteamGifts'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was last updated (UTC)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giveaways',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment primary key'),
    sa.Column('code', sa.String(), nullable=False, comment='Unique SteamGifts giveaway code'),
    sa.Column('url', sa.String(), nullable=False, comment='Full giveaway URL'),
    sa.Column('game_id', sa.Integer(), nullable=True, comment='Steam App ID (foreign key to games)'),
    sa.Column('game_name', sa.String(), nullable=False, comment='Game name (denormalized for display)'),
    sa.Column('price', sa.Integer(), nullable=False, comment='Entry cost in points'),
    sa.Column('copies', sa.Integer(), nullable=False, comment='Number of copies available'),
    sa.Column('end_time', sa.DateTime(), nullable=True, comment='When giveaway ends (UTC)'),
    sa.Column('is_hidden', sa.Boolean(), nullable=False, comment='User manually hid this giveaway'),
    sa.Column('is_entered', sa.Boolean(), nullable=False, comment='Whether we entered this giveaway'),
    sa.Column('is_wishlist', sa.Boolean(), nullable=False, comment="Game is on user's Steam wishlist"),
    sa.Column('is_won', sa.Boolean(), nullable=False, comment='Whether user won this giveaway'),
    sa.Column('won_at', sa.DateTime(), nullable=True, comment='When the win was detected'),
    sa.Column('is_safe', sa.Boolean(), nullable=True, comment='Scam detection result'),
    sa.Column('safety_score', sa.Integer(), nullable=True, comment='Scam detection confidence (0-100)'),
    sa.Column('discovered_at', sa.DateTime(), nullable=False, comment='When we first discovered this'),
    sa.Column('entered_at', sa.DateTime(), nullable=True, comment='When we entered this giveaway'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_giveaways_code'), ['code'], unique=True)

    op.create_table('entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Auto-increment primary key'),
    sa.Column('giveaway_id', sa.Integer(), nullable=False, comment='Foreign key to giveaway'),
    sa.Column('points_spent', sa.Integer(), nullable=False, comment='Points spent on entry'),
    sa.Column('entry_type', sa.String(), nullable=False, comment='Entry method: manual, auto, wishlist'),
    sa.Column('status', sa.String(), nullable=False, comment='Entry status: success, failed, pending'),
    sa.Column('entered_at', sa.DateTime(), nullable=False, comment='When entry was attempted (UTC)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error details if entry failed'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was created (UTC)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='When record was last updated (UTC)'),
    sa.ForeignKeyConstraint(['giveaway_id'], ['giveaways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entries_giveaway_id'), ['giveaway_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_giveaway_id'))

    op.drop_table('entries')
    with op.batch_alter_table('giveaways', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_giveaways_code'))

    op.drop_table('giveaways')
    op.drop_table('settings')
    op.drop_table('scheduler_state')
    op.drop_table('games')
    with op.batch_alter_table('activity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_logs_level'))
        batch_op.drop_index(batch_op.f('ix_activity_logs_created_at'))

    op.drop_table('activity_logs')
    # ### end Alembic commands ###
